version: "3.5"

services:
  carrentalco-administration:
    image: carrentalco-administration:develop
    ports: 
      - 8001:8001
    networks: 
      - main
    container_name: carrentalco-administration
    depends_on:
      - mongo
    environment: 
      - mongo:connectionString=mongodb://mongo:27017
      - ASPNETCORE_ENVIRONMENT=Production

  carrentalco-orders:
    image: carrentalco-orders:develop
    ports: 
      - 8002:8002
    networks: 
      - main
    container_name: carrentalco-orders
    depends_on:
      - mongo
    environment: 
      - mongo:connectionString=mongodb://mongo:27017
      - ASPNETCORE_ENVIRONMENT=Production
      - RentalCarClientSettings:BasePath=http://carrentalco-administration:8001
      - RentalCarClientSettings:RentalCarEndpoint=administrationApi/RentalCars
      - RentalCarClientSettings:RentalCarsEndpoint=administrationApi/RentalCars


  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - main
    volumes:
      - mongo:/data/db

networks:
  main:
    name: carrentalco-network

volumes:
  mongo:
    driver: local
