version: "3.5"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - main
    volumes:
      - mongo:/data/db

networks:
  main:
    name: carrentalco-network

volumes:
  mongo:
    driver: local
